FROM tomcat:8.0-alpine
MAINTAINER Shivani
RUN apk update
RUN apk add wget
RUN wget --user=admin --password=Password12 -O /usr/local/tomcat/webapps/see.war http://localhost:8082/artifactory/rgtestdocker/com/mka
